### ISSUE TITLE
Tab cannot be merged to window

### ISSUE THREAD

**Issue by NeomMob** [rsms/chromium-tabs#9]
Steps to reproduce
- Create a new window
- Add 2 tabs
- Detach one of them to a new window
- try to merge it the the previous window: it does not work

**Comment by liclac** [comment]
Still seems to be happening to me, strangely enough - trying to merge a tab just makes it disappear.

Using Xcode 5.1.1 on OSX 10.9.

**Comment by elklein** [comment]
I think I fixed something like this locally not too long ago. I'll have to try to get the changes back up on GitHub sometime soon-ish. It might help with what you're seeing.

**Comment by rsms** [comment]
@elklein If/when you do, please document what was going on and submit a pull request. Thanks.

**Comment by elklein** [comment]
Have taken a look at my current code, the issue was with weak vs. strong references to the browser in my code. The core fix (for my codebase at least) was to modify CTBrowserWindowController's detachTabToNewWindow to create a strong local reference the the CTBrowser before calling detachTabContentsAtIndex, and then use that instead of browser_ when calling createNewStripWithContents. Basically browser_ is weak, and it's possible that calling detachTabContentsAtIndex might dealloc the CTBrowser as a side-effect, an then you'd wind up in a weird state. I think I also had to modify my app to have strong references to the CTBrowsers as well (I don't remember all the details). Anyway, I'll try to update my repository here on GitHub soon (next day or two) and submit a pull request.

Cheers!

**Comment by rsms** [comment]
Nice work. I'm sure there are plenty of seldomly-hit ownership-related memory bugs in `chromium-tabs` :smiley_cat:

**Comment by elklein** [comment]
@rsms: I know I'm super-super late to the party, but... this has been nagging me on my todo list forever it feels like. Anyway, finally merged by local changes back to github, and created a pull request for it.

Cheers!

**Comment by rsms** [comment]
Project no longer maintained.
